name: mask
channels:
  - defaults
dependencies:
  - matplotlib=2.2.2
  - numpy=1.15.0
  - opencv-python
  - Pillow
  - pip=10.0.1
  - python=3.6.6
  - scikit-image
  - scipy
  - sklearn
  - tensorflow
  - tqdm